services:
  frontend:
    build:
      dockerfile: Dockerfile
    image: resumelly-frontend:latest
    container_name: alpine-frontend
    command: sh -c "echo Hello from Alpine Frontend container && sleep 300"

  backend:
    build:
      dockerfile: Dockerfile
    image: resumelly-backend:latest
    container_name: alpine-backend
    command: sh -c "echo Hello from Alpine Backend container && sleep 300"

  middleend:
    build:
      dockerfile: Dockerfile
    image: resumelly-middleware:latest
    container_name: alpine-middleend
    command: sh -c "echo Hello from Alpine Middleend container && sleep 300"
